<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'Woomp\\Symfony\\Polyfill\\Php72\\' => array($vendorDir . '/symfony/polyfill-php72'),
    'Woomp\\Symfony\\Polyfill\\Intl\\Normalizer\\' => array($vendorDir . '/symfony/polyfill-intl-normalizer'),
    'Woomp\\Symfony\\Polyfill\\Intl\\Idn\\' => array($vendorDir . '/symfony/polyfill-intl-idn'),
    'Woomp\\Psr\\Http\\Message\\' => array($vendorDir . '/psr/http-message/src'),
    'Woomp\\ODS\\' => array($vendorDir . '/oberonlai/wp-metabox/src'),
    'Woomp\\InvoicePorter\\' => array($vendorDir . '/dennykuo/invoice-porter/src'),
    'Woomp\\GuzzleHttp\\Psr7\\' => array($vendorDir . '/guzzlehttp/psr7/src'),
    'Woomp\\GuzzleHttp\\Promise\\' => array($vendorDir . '/guzzlehttp/promises/src'),
    'Woomp\\GuzzleHttp\\' => array($vendorDir . '/guzzlehttp/guzzle/src'),
);
