<?php

// autoload_files.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'dfecedcfcf5021173bed709c3c55d8f3' => $vendorDir . '/ralouphie/getallheaders/src/getallheaders.php',
    '37906b84ddd0ca5ab0e7ebbd14ea9ca8' => $vendorDir . '/symfony/polyfill-intl-normalizer/bootstrap.php',
    '217b819baf4c6745d1fb49f7fc1060a1' => $vendorDir . '/symfony/polyfill-php72/bootstrap.php',
    '375ad191fe90f591d89f6b8dc74562a8' => $vendorDir . '/guzzlehttp/promises/src/functions_include.php',
    'd7b8c9e67d1c1f3db221ceea265ed3be' => $vendorDir . '/guzzlehttp/psr7/src/functions_include.php',
    '81c49e3a9ea5f1d8e2101fb32c29d8db' => $vendorDir . '/symfony/polyfill-intl-idn/bootstrap.php',
    'e621c1cd6378dc90f2d8ae3b9084d633' => $vendorDir . '/guzzlehttp/guzzle/src/functions_include.php',
    'fe3d965ebdea2098f883052665292c2f' => $vendorDir . '/a7/autoload/package.php',
    'c88d4ffe0e90e64bc3c6e3aa09371da2' => $vendorDir . '/yahnis-elsts/plugin-update-checker/load-v5p3.php',
);
